### ISSUE TITLE
Too long line in a commit causes an error

### ISSUE THREAD

**Issue by okkez** [clear-code/git-commit-mailer#5]
For example, from pgroonga/pgroonga.

```
Processing change: ["23484e7020dc1f0d5943ad05c8efc2c9175f20ae", "7ec3f987582469b0de42ab28b86daa3a2ea7f2e7", "refs/heads/master"]

Net::SMTPFatalError: 550 maximum allowed line length is 998 octets, got 1352

/usr/lib/ruby/2.3.0/net/smtp.rb:965:in `check_response'
/usr/lib/ruby/2.3.0/net/smtp.rb:919:in `data'
/usr/lib/ruby/2.3.0/net/smtp.rb:717:in `block in open_message_stream'
/usr/lib/ruby/2.3.0/net/smtp.rb:859:in `rcptto_list'
/usr/lib/ruby/2.3.0/net/smtp.rb:717:in `open_message_stream'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/lib/git-commit-mailer.rb:151:in `block (2 levels) in send_mail'
/usr/lib/ruby/2.3.0/net/smtp.rb:522:in `start'
/usr/lib/ruby/2.3.0/net/smtp.rb:458:in `start'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/lib/git-commit-mailer.rb:150:in `block in send_mail'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/lib/git-commit-mailer.rb:44:in `spend'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/lib/git-commit-mailer.rb:149:in `send_mail'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/lib/git-commit-mailer.rb:1178:in `send_mail'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/lib/git-commit-mailer.rb:1148:in `block in send_all_mails'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/lib/git-commit-mailer.rb:1147:in `each'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/lib/git-commit-mailer.rb:1147:in `send_all_mails'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/bin/git-commit-mailer:58:in `block in <top (required)>'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/lib/git-commit-mailer.rb:44:in `spend'
/home/git-utils/web-hooks-receiver/vendor/bundle/ruby/2.3.0/bundler/gems/git-commit-mailer-ba2a355dd166/bin/git-commit-mailer:53:in `<top (required)>'
bin/git-commit-mailer:17:in `load'
bin/git-commit-mailer:17:in `<main>'
```

**Comment by kou** [comment]
We need to use Base64 when body has long line.

**Comment by kou** [comment]
Done.
